# Generated by Django 3.2.7 on 2021-09-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyses',
            options={'verbose_name': 'Анализ', 'verbose_name_plural': 'Анализы'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
    ]
