# Generated by Django 3.2.7 on 2021-09-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_main', models.CharField(max_length=20, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.analyses')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('is_confirm_consent', models.BooleanField(verbose_name='Согласие на обработку данных')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sex')),
            ],
            options={
                'verbose_name': 'ФИО',
                'verbose_name_plural': 'ФИО',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='analyses',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.patients'),
        ),
    ]
